apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
data:
  config.yml: |
    dbtype: 'sqlite3'
    app:
      authkey: {{ .Values.api.authkey }}
      cryptkey: {{ .Values.api.cryptkey }}