apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-server-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-api
  ports:
  - name: port-21114
    port: 21114
    targetPort: 21114