name: Flutter Monthly Build

on:
  schedule:
    # schedule build every 1st day of each month
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  run-flutter-monthly-build:
    uses: ./.github/workflows/flutter-sctg-build.yaml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "dev"
